### ISSUE TITLE
Menu Link can look the wrong color

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu_d8#13]
The menu link text becomes transparent along with the menu, causing it to not look navy blue.

<img width="285" alt="screen shot 2017-08-07 at 9 52 01 pm" src="https://user-images.githubusercontent.com/9389424/29055615-aacc5b22-7bba-11e7-981d-398a34b68170.png">

**Comment by katrialesser** [comment]
Rebecca can you add a strong opacity: 1 to the menu link itself?

I'll ask Aleni for specs on how the active/current-page/hover gray backgrounds are supposed to be when it's transparent (if they should be full opacity or slightly transparent.

**Comment by Aleniras** [comment]
hmm.. this is tricky. please keep text always at 100%. The buttons can be transparent at 90% if that's possible. Otherwise, keep them at 100%.  Is that doable @katrialesser ?

![image](https://user-images.githubusercontent.com/26605197/30183032-2a8f7348-93d6-11e7-9f59-9f6a1b86730c.png)

**Comment by katrialesser** [comment]
Thanks @Aleniras for providing specs. We can probably do 90% backgrounds without an issue.
This issue should be taken care of in the components so it is fixed for everyone, not just drupal 7.
Issue for it is here: https://github.com/byuweb/byu-theme-components/issues/317
