### ISSUE TITLE
White Strip Under Footer

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu_d8#17]
Even on a full length page, there is a very slim white line underneath the blue footer. You can't see it in the screen shot, but go to [photo-dev2.byu.edu](https://photo-dev2.byu.edu) and you can see it.

<img width="218" alt="screen shot 2017-08-10 at 8 59 06 am" src="https://user-images.githubusercontent.com/9389424/29176942-9c0b53a8-7daa-11e7-9c45-7811cc667838.png">

**Comment by katrialesser** [comment]
@bmorgan296  I can't see this issue, even on photo-dev2.byu.edu. What browser are you using?
I've checked chrome, firefox and edge.

**Comment by rburkey87** [comment]
I'm only seeing it in IE and it refuses to fix

**Comment by rburkey87** [comment]
Also not seeing it on the photo dev site (except in IE11), but I'm seeing it in some of my own test sites.
