### ISSUE TITLE
Additional Padding in Blue Footer

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu_d8#18]
There is additional padding in the blue footer between the Brigham Young University text and the contact information text.

**Drupal 8**:
<img width="465" alt="screen shot 2017-08-10 at 9 03 47 am" src="https://user-images.githubusercontent.com/9389424/29177104-0031fe22-7dab-11e7-9bff-981acab48f43.png">

**Components**:
<img width="447" alt="screen shot 2017-08-10 at 9 04 08 am" src="https://user-images.githubusercontent.com/9389424/29177113-066801e2-7dab-11e7-896b-7ae38b13c8d1.png">

**Comment by katrialesser** [comment]
Hmm. I actually think it looks better with the padding but i'm looking into why it is different. That part is completely components so I don't know.

**Comment by katrialesser** [comment]
This is actually probably something we should fix in the components. if the theme has a line-height set generally, then it has too much space. If we add `line-height: 12px;` where we have `font-size: 12px`  under 
.university-footer { ...} then it should be fixed.

**Comment by katrialesser** [comment]
opened this issue for the components: https://github.com/byuweb/byu-theme-components/issues/315
