### ISSUE TITLE
< 4 menu items center aligned

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu_d8#20]
When there are only three menu items, they are center aligned rather than being left aligned according to the design spec.

<img width="1210" alt="screen shot 2017-08-11 at 8 26 28 pm" src="https://user-images.githubusercontent.com/9389424/29237094-28b551d0-7ed4-11e7-9ae1-ba852ec27bf7.png">

I checked and this is not an issue with the components.

**Comment by rburkey87** [comment]
Looking into this. If you add the `left-align` attribute to the menu manually, it works, but I'm trying to figure out why it's not printing that attribute. Also why the `is-active` class is showing up, but no styling is applying.

**Comment by rburkey87** [comment]
@bmorgan296 - I think I'm starting to figure this out. The `left-align` attribute prints if you go down to 2 menu items (or 1). I think that random empty menu item is still there (even when not showing), so it's making the JS count 4 items when there's only 3. So we've got to figure out the phantom menu item.
