### ISSUE TITLE
Put up all the documentation on webcommunity website

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu_d8#43]
also reference

https://www.drupal.org/docs/8/theming-drupal-8/creating-a-drupal-8-sub-theme-or-sub-theme-of-sub-theme

and definitely this:
https://www.drupal.org/docs/8/theming-drupal-8/adding-stylesheets-css-and-javascript-js-to-a-drupal-8-theme

I would love your guy's help on making sure we have everything helpful documented.

**Comment by katrialesser** [comment]
Blake has reviewed. @sher1 can you review t and then tell us if there's anything to add/adjust?

**Comment by katrialesser** [comment]
Katria needs to update about subtheming after i make the template fix - dont forget!

**Comment by blakemorgan** [comment]
Getting correct in the redesign. Closing.
