### ISSUE TITLE
Null Array

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu_d8#45]
This error sometimes appears when a page is loading. Line 465 is `$font_three = theme_get_setting('font_three');`. That line of code seems to be correct, so the `theme_get_setting()` function in Drupal core may be missing a null check.

<img width="718" alt="screen shot 2017-10-02 at 7 52 25 am" src="https://user-images.githubusercontent.com/9389424/31080754-e96b7770-a746-11e7-828e-b4681f227616.png">

**Comment by katrialesser** [comment]
It looks like this is for font selection option - you should make sure you have gone into theme settings and set something for each font option.
![image](https://user-images.githubusercontent.com/12898896/31085943-b13172ce-a755-11e7-97c9-1d6aa35386d2.png)

**Comment by katrialesser** [comment]
Likely the font setting for H3's.

**Comment by bmorgan296** [comment]
Does that mean I need to change each setting or can I just leave the default?

**Comment by katrialesser** [comment]
it means that once you install you have to click save at least once in the theme settings. have you done so?
Maybe it wants you to click into the field once and save.

Let me know if you have done that and if that works.

From my experience, as long as you save all the theme settings once there isn't a problem.

**Comment by bmorgan296** [comment]
That worked!
