### ISSUE TITLE
Search Bar gone in Chrome

### ISSUE THREAD

**Issue by shawnpaw** [byuweb/byu_d8#49]
I'm running Google Chrome Version 61.0.3163.100 (Official Build) (64-bit) and the search bar is gone but the icon is there. It seems to work in firefox. Have not tried it in other browsers.

**Comment by katrialesser** [comment]
I believe this is a components issue that @ThatJoeMoore is looking at.

**Comment by katrialesser** [comment]
It was introduced in a recent version of chrome. Joe already fixed it and it is in the master version of the components, but not in the latest release yet. If you switch to the master version you'll have the fix @shawnpaw .

**Comment by shawnpaw** [comment]
Thanks! You are fast!
