### ISSUE TITLE
add sticky footer adjustment for normal admin menu, admin toolbar module

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu_d8#59]
1. add js snippet to check if admin menu plain is there - add a class to body or html
2. add js snippet to check if admin toolbar module is there - #toolbar-administration - add a different class to body or html

3. add js adjusting the sticky footer code to 
min-height: calc(100vh - 80px); etc

**Comment by rburkey87** [comment]
`min-height: calc(100vh - 80px)` doesn't work due to incompatible units

**Comment by katrialesser** [comment]
done w recent merge.
